#!/bin/bash

LN="================================================================================"

CLR='\033[0m'

GRN='\033[0;32m'
YLW='\033[1;33m'


# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37

function print_header {
    printf "\n${YLW}${LN}\n\u25BA ${1}\n${LN}${CLR}\n\n"
}

function check {
    echo "" # $1
}

print_header "RUNNING TESTS"
coverage run manage.py test
check $?

print_header "COVERAGGE REPORT"
coverage report
check $?

# create html report
coverage html -d _coverage_html
#firefox _coverage_html/index.html

print_header "Static Conde Analysis"
flake8
check $?
