# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 16:30
from __future__ import unicode_literals

import Lenses.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('names', models.TextField()),
                ('file', models.FileField(upload_to=Lenses.models.hash_upload)),
                ('scidata', models.TextField()),
                ('imgdata', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.TextField(default=None, null=True)),
                ('edit_history', models.TextField()),
            ],
        ),
    ]
